proto tcp-server
ifconfig-pool-persist "./src/log/ipp.txt"
keepalive 10 120
user nobody
group nogroup
persist-key
persist-tun

verb 3
mute 10
ca "./src/keys/root.crt"
key "./src/keys/server.key"
cert "./src/keys/server.crt"
dh "./src/keys/dh.pem"
management localhost 7505
tls-version-min 1.2
data-ciphers AES-256-GCM:AES-256-CBC
cipher AES-256-GCM
auth SHA256
remote-cert-tls client
port 1194
dev tun0
topology subnet
server 10.8.0.0 255.255.255.0
push "dhcp-option DNS 1.1.1.1"
push "dhcp-option DNS 1.0.0.1"
push "route 192.168.0.0 255.255.255.0"

script-security 2

